version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: argo_data
      POSTGRES_USER: argo_user
      POSTGRES_PASSWORD: argo_password
    volumes:
      - ./backend/storage/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U argo_user -d argo_data"]
      interval: 5s
      timeout: 5s
      retries: 5