version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: argo_data
      POSTGRES_USER: argo_user
      POSTGRES_PASSWORD: argo_password
    volumes:
      - ./backend/storage/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app